[project]
authors = ["gabrieldemarmiesse <gabrieldemarmiesse@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "zipfile"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "==25.4.0.dev2025051505"
