[project]
authors = ["gabrieldemarmiesse <gabrieldemarmiesse@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/mojo-community"]
name = "zipfile"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "mojo test -I . tests/"
format = "mojo format"

[dependencies]
max = ">=25.3.0.dev2025042605"
pre-commit = ">=4.2.0,<5"
mojo-zlib = ">=0.1.1,<0.2"
